# Generated by Django 5.0.4 on 2025-05-08 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='planes_img/'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='capacidad_maxima',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='lugar',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='planes_unidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
