# Generated by Django 5.0.4 on 2025-05-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_plan_imagen_alter_plan_capacidad_maxima_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='capacidad_maxima',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
