# Generated by Django 5.0.4 on 2025-05-08 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0003_alter_plan_capacidad_maxima'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='capacidad_maxima',
        ),
    ]
