# Generated by Django 5.0.4 on 2025-05-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0004_remove_plan_capacidad_maxima'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plazas_disponibles',
            field=models.IntegerField(default=1),
        ),
    ]
